version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: tank_pg
    environment:
    - POSTGRES_USER=tankuser
    - POSTGRES_PASSWORD=cst4Ever
    - POSTGRES_DB=tankdb
    - PGPORT=6900
    ports:
      - "6900:6900" 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
